made gv compatible with subdirectories in /var/rid/meta

diff --git a/bin/gv b/bin/gv
--- a/bin/gv
+++ b/bin/gv
@@ -2,4 +2,18 @@
 # gv = get version
 # $1 = target package
 
-echo $(grep "VERS=" "$RIDMETA/$1" | sed -E 's/^.*="(.*)"$/\1/')
+find_metafile() {
+  local metafile="$1"
+  local result
+  result=$(find "$RIDMETA" -type f -name "$metafile" ! -name "README.md" ! -name "LICENSE" 2>/dev/null)
+  
+  if [ -z "$result" ]; then
+    echo "Metafile '$metafile' not found in $RIDMETA"
+    exit 1
+  fi
+  echo "$result"
+}
+
+METAFILE="$(find_metafile "$1")"
+
+echo $(grep "VERS=" "$METAFILE" | sed -E 's/^.*="(.*)"$/\1/')
