fixed an inconsistency with update directions

diff --git a/bin/mint b/bin/mint
--- a/bin/mint
+++ b/bin/mint
@@ -56,6 +56,8 @@ case $1 in
       echo "Updating $NAME (default)..."
       ins
     else
+      pushd "$RIDBUILDING/$NAME-$VERS" > /dev/null || die "Failed to enter build directory"
+
       echo "Updating $NAME (custom)..."
       eval "$UDIR"
     fi
