env var support

diff --git a/bin/mint b/bin/mint
--- a/bin/mint
+++ b/bin/mint
@@ -2,13 +2,17 @@
 
 METAFILE="$2"
 
+[ -z $RIDHOME ] && RIDHOME="/etc/rid"
+[ -z $RIDBUILDING ] && RIDBUILDING="/tmp/rid/building"
+[ -z $RIDTMP ] && RIDTMP="/tmp/rid"
+
 function pre {
   bv=$(compgen -v)
-  . /etc/rid/env || { echo "Failed to source /etc/rid/env"; exit 1; }
-  . /etc/rid/meta/"$METAFILE" || { die "Failed to source /etc/rid/meta/$METAFILE"; exit 1; }
+  . $RIDHOME/env || { echo "Failed to source $RIDHOME/env"; exit 1; }
+  . $RIDHOME/meta/"$METAFILE" || { die "Failed to source $RIDHOME/meta/$METAFILE"; exit 1; }
   av=$(compgen -v)
 
-  rm -f /tmp/rid/failed
+  rm -f $RIDTMP/failed
 }
 
 function cleanup {
@@ -17,12 +21,12 @@ function cleanup {
       unset "$var"
     fi
   done
-  rm -rf /tmp/rid/building/$NAME-$VERS
+  rm -rf "$RIDBUILDING/$NAME-$VERS"
 }
 
 function ins {
   check_perms
-  pushd /tmp/rid/building/$NAME-$VERS > /dev/null || { die "Failed to enter build directory"; exit 1; }
+  pushd "$RIDBUILDING/$NAME-$VERS" > /dev/null || { die "Failed to enter build directory"; exit 1; }
 
   echo "Installing $NAME-$VERS..."
   eval "$IDIR"
