more unique die message

diff --git a/env b/env
--- a/env
+++ b/env
@@ -39,7 +39,7 @@ pathappend () {
 }
 
 die() {
-    echo "Error: $1" >&2
+    echo "Died with error: $1" >&2
     touch /tmp/rid/failed
     exit 1
 }
